title: OS1RIS
logo: /asset/logo.png
description: Some text that i will put later. Ask ur friend if they have idea
show_downloads: true
theme: jekyll-theme-minimal
layout: page
title: "CURTIN-CTF-2023"
permalink: /curtin-ctf-2023
