title: OS1RIS
logo: /assets/logo.png   # Assuming your logo image is in the "assets" folder
description: Some text that I will put later. Ask your friend if they have an idea.
show_downloads: true
theme: jekyll-theme-minimal
layout: page
title: "CURTIN-CTF-2023"
permalink: /curtin-ctf-2023
